### ISSUE TITLE
Missing dh_shlibdeps from Tutorial 3

### ISSUE THREAD

**Issue by agfline** [phusion/debian-packaging-for-the-modern-developer#2]
Hi and thanks for those tutorials, they helped me a lot.

In Tutorial 3, you forgot the `dh_shlibdeps` command in the **rules** file, wich is supposed to eval the `${shlibs:Depends}` variable.

This is why you get from the output :
```
dpkg-gencontrol: warning: Depends field of package hello: unknown substitution variable ${shlibs:Depends}
```

**Comment by raidoz** [comment]
Can confirm that adding dh_shlibdeps fixes the warning and missing deps.
